version: "3.9"

services:

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/source:/usr/src/frontend
      - node_modules:/usr/src/frontend/node_modules
    working_dir: /usr/src/frontend
    restart: always
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

volumes:
    node_modules:
