version: "3.9"

services:

  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/source:/usr/src/frontend
      - node_modules:/usr/src/frontend/node_modules
    working_dir: /usr/src/frontend
    restart: always
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/app:/usr/src/backend/app
    ports:
      - 5000:5000

volumes:
    node_modules:
