import Head from "next/head";
import { motion } from "framer-motion";

import styles from "@/styles/about.module.css";

const about = () => {
  return (
    <>
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15 }}>
        <Head>
          <title>about : ES Harmony</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.container}>
          <div className={styles.wrapper}>
            <div>
              <h2>1. ES Harmonyについて</h2>
            </div>
            <div id="ai">
              <h2>2. AI技術</h2>
            </div>
          </div>
        </main>
      </motion.div>
    </>
  );
};

export default about;
