import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";

import Header from "@/components/Header/Header";
import ButtonArea from "@/components/molecules/ButtonArea/ButtonArea";
import Button from "@/components/atoms/Button/Button";
import StudentCard from "@/components/molecules/StudentCard/StudentCard";

import { StudentData } from "@/types/types";
import { getData } from "@/lib/getData";

import { Noto_Sans_JP } from "next/font/google";

const notojp = Noto_Sans_JP({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
    variable: "--font-notojp",
    display: "swap",
});

type Props = {
    studentData: StudentData[];
};

export default function Home({ studentData }: Props) {
    return (
        <>
            <Head>
                <title>ES Harmony</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${notojp.variable}`}>
                <Header />
                <div className={styles.container}>
                    <ButtonArea>
                        <Button text="Button" />
                        <Button text="Button" />
                    </ButtonArea>
                    <div className={styles.cardArea}>
                        {studentData.map((one_studentData: StudentData, index: number) => (
                            <StudentCard key={index} studentData={one_studentData} />
                        ))}
                    </div>
                </div>
            </main>
        </>
    );
}
{
    /* TODO: SSGによるデータの取得 */
}

export const getStaticProps: GetStaticProps<{
    studentData: StudentData[];
}> = async () => {
    const studentData: StudentData[] = await getData();
    return {
        props: { studentData },
    };
};
