import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Header from "@/components/Header/Header";
import ButtonArea from "@/components/molecules/ButtonArea/ButtonArea";
import Button from "@/components/atoms/Button/Button";
import StudentCard from "@/components/molecules/StudentCard/StudentCard";

{
    /* TODO: testの削除 */
}
import { testStudentData } from "@/test/test_data";

import { Noto_Sans_JP } from "next/font/google";

const notojp = Noto_Sans_JP({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
    variable: "--font-notojp",
    display: "swap",
});

export default function Home() {
    return (
        <>
            <Head>
                <title>ES Harmony</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${notojp.variable}`}>
                <Header />
                <div className={styles.container}>
                    <ButtonArea>
                        <Button text="Button" />
                        <Button text="Button" />
                    </ButtonArea>
                    <div className={styles.cardArea}>
                        {/* TODO: データの表示処理 */}
                        <StudentCard data={testStudentData} />
                    </div>
                </div>
            </main>
        </>
    );
}
{
    /* TODO: SSGによるデータの取得 */
}
