import Head from "next/head";
import { useState, useEffect } from "react";

import styles from "@/styles/Home.module.css";

import Header from "@/components/Header/Header";
import ButtonArea from "@/components/molecules/ButtonArea/ButtonArea";
import Button from "@/components/atoms/Button/Button";
import StudentCard from "@/components/molecules/StudentCard/StudentCard";

import { StudentData } from "@/types/types";
import { getData } from "@/lib/getData";

import { Noto_Sans_JP } from "next/font/google";

import { motion } from "framer-motion";

const notojp = Noto_Sans_JP({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
    variable: "--font-notojp",
    display: "swap",
});

type Props = {
    studentData: StudentData[];
};

export default function Home({ studentData }: Props) {
    const [sort, setSort] = useState<string>("match_level");
    const [order, setOrder] = useState<string>("desc");

    const onClickOrder = () => {
        if (order === "desc") {
            setOrder("asc");
        } else {
            setOrder("desc");
        }
    };

    const onClickSort = () => {
        if (sort === "match_level") {
            setSort("AI_degree");
        } else {
            setSort("match_level");
        }
    };

    const sortData = () => {
        studentData.sort((a, b) => {
            console.log(sort);
            console.log(order);
            if (order === "desc") {
                return a[sort] - b[sort];
            } else {
                return b[sort] - a[sort];
            }
        });
    };

    useEffect(() => {
        sortData();
    }, [sort, order, studentData]);

    useEffect(() => {
        sortData();
    }, []);

    const list = {
        visible: {
            opacity: 1, // 不透明度1
            transition: {
                staggerChildren: 0.1, // 子要素に1秒間隔でアニメーションを行う
            },
        },
        hidden: {
            opacity: 0, // 不透明度0
        },
    };

    const item = {
        visible: { x: 0 },
        hidden: { x: -300 },
    };
    return (
        <>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15 }}>
                <Head>
                    <title>ES Harmony</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className={`${styles.main} ${notojp.variable}`}>
                    <Header />
                    <div className={styles.container}>
                        <ButtonArea>
                            {sort}
                            <Button text={sort == "AI_degree" ? "AI度" : "マッチ度"} onClickFunc={onClickSort} />
                            <Button text={order == "asc" ? "昇順↑" : "降順↓"} onClickFunc={onClickOrder} />
                        </ButtonArea>
                        <div className={styles.cardArea}>
                            <motion.ol variants={list} initial="hidden" animate="visible">
                                {studentData.map((one_studentData: StudentData, index: number) => (
                                    <motion.li variants={item} key={index}>
                                        <motion.div transition={{ duration: 0.25 }} whileHover={{ scale: 1.05 }} key={index}>
                                            <StudentCard studentData={one_studentData} />
                                        </motion.div>
                                    </motion.li>
                                ))}
                            </motion.ol>
                        </div>
                    </div>
                </main>
            </motion.div>
        </>
    );
}

export const getStaticProps = async () => {
    const studentData: StudentData = await getData();
    return {
        props: { studentData },
    };
};
